// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Menu_Project

#include "../ui.h"

// void ui_ScreenGeneric_screen_init(void)
// {
//     ui_ScreenGeneric = lv_obj_create(NULL);
//     lv_obj_clear_flag(ui_ScreenGeneric, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//     ui_Label9 = lv_label_create(ui_ScreenGeneric);
//     lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label9, -80);
//     lv_obj_set_y(ui_Label9, -140);
//     lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label9, "Status 1");
//     lv_obj_set_style_outline_color(ui_Label9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_outline_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_outline_width(ui_Label9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_outline_pad(ui_Label9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_left(ui_Label9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_right(ui_Label9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_top(ui_Label9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_bottom(ui_Label9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label10 = lv_label_create(ui_ScreenGeneric);
//     lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label10, 0);
//     lv_obj_set_y(ui_Label10, -100);
//     lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label10, "MENU TITLE");
//     lv_obj_set_style_outline_color(ui_Label10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_outline_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_outline_width(ui_Label10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_outline_pad(ui_Label10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_left(ui_Label10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_right(ui_Label10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_top(ui_Label10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_bottom(ui_Label10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label11 = lv_label_create(ui_ScreenGeneric);
//     lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label11, 80);
//     lv_obj_set_y(ui_Label11, -140);
//     lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label11, "Status 2");
//     lv_obj_set_style_outline_color(ui_Label11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_outline_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_outline_width(ui_Label11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_outline_pad(ui_Label11, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_left(ui_Label11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_right(ui_Label11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_top(ui_Label11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_bottom(ui_Label11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label12 = lv_label_create(ui_ScreenGeneric);
//     lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label12, -50);
//     lv_obj_set_y(ui_Label12, -60);
//     lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label12, "A   Menu Item");
//     lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label13 = lv_label_create(ui_ScreenGeneric);
//     lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label13, -50);
//     lv_obj_set_y(ui_Label13, -20);
//     lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label13, "B   Menu Item");
//     lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label14 = lv_label_create(ui_ScreenGeneric);
//     lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label14, -50);
//     lv_obj_set_y(ui_Label14, 20);
//     lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label14, "C   Menu Item");
//     lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label15 = lv_label_create(ui_ScreenGeneric);
//     lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label15, -50);
//     lv_obj_set_y(ui_Label15, 60);
//     lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label15, "D  Menu Item");
//     lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label16 = lv_label_create(ui_ScreenGeneric);
//     lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label16, 0);
//     lv_obj_set_y(ui_Label16, 97);
//     lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label16, "Instructions");

//     ui_Label17 = lv_label_create(ui_ScreenGeneric);
//     lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label17, 0);
//     lv_obj_set_y(ui_Label17, 130);
//     lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label17, "Selection");
//     lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_outline_color(ui_Label17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_outline_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_outline_width(ui_Label17, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_outline_pad(ui_Label17, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_left(ui_Label17, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_right(ui_Label17, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_top(ui_Label17, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_bottom(ui_Label17, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

lv_obj_t *create_menu_screen(const char *status_1_text, const char *status_2_text, const char *title_text, const char *menu_a_text,
                             const char *menu_b_text, const char *menu_c_text, const char *menu_d_text, const char *instru_text, const char *select_text)
{
    lv_obj_t *screen = lv_obj_create(NULL);

    lv_obj_t *status_1_Label = lv_label_create(screen);
    lv_obj_set_width(status_1_Label, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(status_1_Label, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(status_1_Label, -80);
    lv_obj_set_y(status_1_Label, -140);
    lv_obj_set_align(status_1_Label, LV_ALIGN_CENTER);
    lv_label_set_text(status_1_Label, status_1_text);
    lv_obj_set_style_outline_color(status_1_Label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(status_1_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(status_1_Label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(status_1_Label, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(status_1_Label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(status_1_Label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(status_1_Label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(status_1_Label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *status_2_Label = lv_label_create(screen);
    lv_obj_set_width(status_2_Label, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(status_2_Label, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(status_2_Label, 0);
    lv_obj_set_y(status_2_Label, -100);
    lv_obj_set_align(status_2_Label, LV_ALIGN_CENTER);
    lv_label_set_text(status_2_Label, status_2_text);
    lv_obj_set_style_outline_color(status_2_Label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(status_2_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(status_2_Label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(status_2_Label, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(status_2_Label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(status_2_Label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(status_2_Label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(status_2_Label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *title_label = lv_label_create(screen);
    lv_obj_set_width(title_label, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(title_label, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(title_label, 80);
    lv_obj_set_y(title_label, -140);
    lv_obj_set_align(title_label, LV_ALIGN_CENTER);
    lv_label_set_text(title_label, title_text);
    lv_obj_set_style_outline_color(title_label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(title_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(title_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(title_label, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(title_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(title_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(title_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(title_label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *menu_a_Label = lv_label_create(screen);
    lv_obj_set_width(menu_a_Label, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(menu_a_Label, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(menu_a_Label, 10);
    lv_obj_set_y(menu_a_Label, -60);
    lv_obj_set_align(menu_a_Label, LV_ALIGN_LEFT_MID);
    //lv_obj_align(menu_a_Label, LV_ALIGN_LEFT_MID, 0, 0);
    lv_label_set_text(menu_a_Label, menu_a_text);
    lv_obj_set_style_text_font(menu_a_Label, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *menu_b_Label = lv_label_create(screen);
    lv_obj_set_width(menu_b_Label, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(menu_b_Label, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(menu_b_Label, 10);
    lv_obj_set_y(menu_b_Label, -20);
    lv_obj_set_align(menu_b_Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(menu_b_Label, menu_b_text);
    lv_obj_set_style_text_font(menu_b_Label, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *menu_c_Label = lv_label_create(screen);
    lv_obj_set_width(menu_c_Label, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(menu_c_Label, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(menu_c_Label, 10);
    lv_obj_set_y(menu_c_Label, 20);
    lv_obj_set_align(menu_c_Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(menu_c_Label, menu_c_text);
    lv_obj_set_style_text_font(menu_c_Label, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *menu_d_Label = lv_label_create(screen);
    lv_obj_set_width(menu_d_Label, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(menu_d_Label, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(menu_d_Label, 10);
    lv_obj_set_y(menu_d_Label, 60);
    lv_obj_set_align(menu_d_Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(menu_d_Label, menu_d_text);
    lv_obj_set_style_text_font(menu_d_Label, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *instr_Label = lv_label_create(screen);
    lv_obj_set_width(instr_Label, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(instr_Label, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(instr_Label, 0);
    lv_obj_set_y(instr_Label, 95);
    lv_obj_set_align(instr_Label, LV_ALIGN_CENTER);
    lv_label_set_text(instr_Label, instru_text);
    lv_obj_set_style_text_font(instr_Label, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *select_Label = lv_label_create(screen);
    lv_obj_set_width(select_Label, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(select_Label, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(select_Label, 0);
    lv_obj_set_y(select_Label, 130);
    lv_obj_set_align(select_Label, LV_ALIGN_CENTER);
    lv_label_set_text(select_Label, select_text);
    lv_obj_set_style_text_font(select_Label, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(select_Label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(select_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(select_Label, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(select_Label, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(select_Label, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(select_Label, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(select_Label, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(select_Label, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    // lv_obj_t* title_label = lv_label_create(screen);
    // lv_label_set_text(title_label, title);
    // lv_obj_align(title_label, LV_ALIGN_TOP_MID, 0, 20);

    // lv_obj_t* btn1 = lv_btn_create(screen);
    // lv_obj_t* btn1_label = lv_label_create(btn1);
    // lv_label_set_text(btn1_label, btn1_text);
    // lv_obj_align(btn1, LV_ALIGN_CENTER, 0, -40);

    // lv_obj_t* btn2 = lv_btn_create(screen);
    // lv_obj_t* btn2_label = lv_label_create(btn2);
    // lv_label_set_text(btn2_label, btn2_text);
    // lv_obj_align(btn2, LV_ALIGN_CENTER, 0, 0);

    // lv_obj_t* btn3 = lv_btn_create(screen);
    // lv_obj_t* btn3_label = lv_label_create(btn3);
    // lv_label_set_text(btn3_label, btn3_text);
    // lv_obj_align(btn3, LV_ALIGN_CENTER, 0, 40);

    return screen;
}

// void ui_ScreenGeneric_screen_init(void)
// {
//     ui_ScreenGeneric = lv_obj_create(NULL);
//     lv_obj_clear_flag(ui_ScreenGeneric, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

//     ui_Label9 = lv_label_create(ui_ScreenGeneric);
//     lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label9, -80);
//     lv_obj_set_y(ui_Label9, -140);
//     lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label9, "Status 1");
//     lv_obj_set_style_outline_color(ui_Label9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_outline_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_outline_width(ui_Label9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_outline_pad(ui_Label9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_left(ui_Label9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_right(ui_Label9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_top(ui_Label9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_bottom(ui_Label9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label10 = lv_label_create(ui_ScreenGeneric);
//     lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label10, 0);
//     lv_obj_set_y(ui_Label10, -100);
//     lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label10, "MENU TITLE");
//     lv_obj_set_style_outline_color(ui_Label10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_outline_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_outline_width(ui_Label10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_outline_pad(ui_Label10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_left(ui_Label10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_right(ui_Label10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_top(ui_Label10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_bottom(ui_Label10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label11 = lv_label_create(ui_ScreenGeneric);
//     lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label11, 80);
//     lv_obj_set_y(ui_Label11, -140);
//     lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label11, "Status 2");
//     lv_obj_set_style_outline_color(ui_Label11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_outline_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_outline_width(ui_Label11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_outline_pad(ui_Label11, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_left(ui_Label11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_right(ui_Label11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_top(ui_Label11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_bottom(ui_Label11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label12 = lv_label_create(ui_ScreenGeneric);
//     lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label12, -50);
//     lv_obj_set_y(ui_Label12, -60);
//     lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label12, "A   Menu Item");
//     lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label13 = lv_label_create(ui_ScreenGeneric);
//     lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label13, -50);
//     lv_obj_set_y(ui_Label13, -20);
//     lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label13, "B   Menu Item");
//     lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label14 = lv_label_create(ui_ScreenGeneric);
//     lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label14, -50);
//     lv_obj_set_y(ui_Label14, 20);
//     lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label14, "C   Menu Item");
//     lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label15 = lv_label_create(ui_ScreenGeneric);
//     lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label15, -50);
//     lv_obj_set_y(ui_Label15, 60);
//     lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label15, "D  Menu Item");
//     lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

//     ui_Label16 = lv_label_create(ui_ScreenGeneric);
//     lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label16, 0);
//     lv_obj_set_y(ui_Label16, 97);
//     lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label16, "Instructions");

//     ui_Label17 = lv_label_create(ui_ScreenGeneric);
//     lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
//     lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
//     lv_obj_set_x(ui_Label17, 0);
//     lv_obj_set_y(ui_Label17, 130);
//     lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
//     lv_label_set_text(ui_Label17, "Selection");
//     lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_outline_color(ui_Label17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_outline_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_outline_width(ui_Label17, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_outline_pad(ui_Label17, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_left(ui_Label17, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_right(ui_Label17, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_top(ui_Label17, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
//     lv_obj_set_style_pad_bottom(ui_Label17, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

// uic_Label9 = ui_Label9;
// uic_Label10 = ui_Label10;
// uic_Label11 = ui_Label11;
// uic_Label12 = ui_Label12;
// uic_Label13 = ui_Label13;
// uic_Label14 = ui_Label14;
// uic_Label15 = ui_Label15;
// uic_Label16 = ui_Label16;
// uic_Label17 = ui_Label17;

// }