// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "stdio.h"

// #include "esp_timer.h"
// #include <driver/timer.h>

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
void ui_event_Button1(lv_event_t *e);
lv_obj_t *ui_Button1;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Label3;
lv_obj_t *ui_TextArea1;
void keypad_event_cb(lv_event_t *e);
lv_indev_t *indev_kp;
lv_group_t *group_kp;

// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t *ui_Screen2;
void ui_event_Button2(lv_event_t *e);
lv_obj_t *ui_Button2;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Label4;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenGeneric
void ui_ScreenGeneric_screen_init(void);
lv_obj_t *ui_ScreenGeneric;
lv_obj_t *ui_Label9;
lv_obj_t *ui_Label10;
lv_obj_t *ui_Label11;
lv_obj_t *ui_Label12;
lv_obj_t *ui_Label13;
lv_obj_t *ui_Label14;
lv_obj_t *ui_Label15;
lv_obj_t *ui_Label16;
lv_obj_t *ui_Label17;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 1
#error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    // if (event_code == LV_EVENT_PRESSED) {
    //     event_code = LV_EVENT_CLICKED;
    // }
    if (event_code == LV_EVENT_CLICKED)
    {
        if (lv_scr_act() == ui_Screen1)
        {
            printf("Button1 clicked\n");
            _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
        }
    }
}

void ui_event_Button2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        if (lv_scr_act() == ui_Screen2)
        {
            printf("Button2 clicked\n");
            _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
        }
    }
}

void keypad_event_cb(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t *obj = lv_event_get_target(e);
    if (code == LV_EVENT_KEY)
    {
        uint32_t key = lv_event_get_key(e);
        if (key >= '0' && key <= '9')
        {
            char str[2] = {key, '\0'};
            // lv_textarea_add_text(obj, str);
            uint8_t cch;
            cch = key;
            printf("Key pressed: %c\n", cch);
        }
        else if (key == LV_KEY_BACKSPACE)
        {
            lv_textarea_del_char(obj);
        }
    }
}

///////////////////// SCREENS ////////////////////

void switch_screen(lv_obj_t* screen) {
    lv_scr_load_anim(screen, LV_SCR_LOAD_ANIM_FADE_ON, 1500, 0, true);
    //lv_scr_load(screen);
}


void ui_init(void)
{
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                              false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    lv_obj_t *screen1 = create_menu_screen("Status 1", "Screen 1 Menu", "Status 2", "A  Pin Number", "B  Fingerprint", "C  Face Recognition", "D  Other Screen", "Instructions Go Here", "Selection");
    lv_obj_t *screen2 = create_menu_screen("Status 1", "Screen 2 Menu", "Status 2", "A  Pin slumber", "B  Fingerpronto", "C  Farce Recognition", "D  Back Screen", "Instructions Go Here", "Selection");
    // ui_ScreenGeneric_screen_init();
    // ui_ScreenGeneric_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    //lv_disp_load_scr(ui_Screen1);
    lv_scr_load_anim(screen1, LV_SCR_LOAD_ANIM_FADE_ON, 1500, 0, true);
    //vTaskDelay(pdMS_TO_TICKS(1000));
    switch_screen(screen2);

}
